### ISSUE TITLE
paste only works once, no copy

### ISSUE THREAD

**Issue by notuntoward** [orgzly/documentation#10]
On the outline display, I can paste a heading I've cut one time, and the next time I use the paste button, the paste doesn't happen and I see a "nothing to paste" message on the bottom.  In emacs org-mode, I frequently paste several copies of the same headline so it would be nice to be able to do that here as well.

Also, there's no copy icon.  This is another thing that makes it impossible to copy things more than once (you must delete a headline first in order to get it into the paste buffer).

**Comment by nevenz** [comment]
Yeah these are planned, see orgzly/orgzly-android#47

This repository is for documentation BTW.
