### ISSUE TITLE
Search with Space

### ISSUE THREAD

**Issue by DorKeinath** [orgzly/documentation#14]
How can I search for something containing a space? 
For example if I've got a Notbook called "This notebook"
`b.This notebook`
doesn't work.

**Comment by offgridauthor** [comment]
Did you try: b."This notebook"

I don't use spaces, but I just tried that for a notebook and it worked for me.

**Comment by DorKeinath** [comment]
Oh, yes! Thank you! (I tried only with simple ' '.)
