### ISSUE TITLE
TODO states must be specified in setting to be used in search

### ISSUE THREAD

**Issue by blaedj** [orgzly/documentation#5]
~~The documentation doesn't mention this, but it seems that searching by state (e.g. `i.todo`) doesn't support states containing dashes. For example, I have todo's with the state IN-PROGRESS, but creating a search `i.in-progress` does not pull up any results.~~

It turns out that if you add 'IN-PROGRESS' to the list under 'Settings -> Notes -> States', then the search `i.in-progress` works as expected. I left my original note above for posterity, but maybe the documentation could mention this?

Thanks for making the best mobile org-viewer out there!

**Comment by blaedj** [comment]
let me know if you are open to a PR and I'll make one.

**Comment by nevenz** [comment]
Yes, if not specified in Settings, keywords are not really recognized as states at all, they end up being part of the title. You can't search by them, choose them from the menu, they are not colored etc.

Sure, explaining this would be great, thanks!

**Comment by blaedj** [comment]
Thanks!
